<?php
$labels['spam_vpopmaild'] = "Protecció contra Spam";
$labels['spam_on_off'] = "Activa/desactiva protecció contra Spam";
$labels['detection'] = "Activa protecció contra Spam";
$labels['delete'] = "Suprimeix els missatges que són Spam";
$labels['success'] = "S'ha desat correctament";
$labels['save_error'] = "S'ha produït un error mentre es desava";
$labels['load_error'] = "S'ha produït un error mentre es carregava";
