<?php
$labels['spam_vpopmaild'] = "Protección de spam";
$labels['spam_on_off'] = "Habilitar/deshabilitar protección de spam";
$labels['detection'] = "Habilitar detección de spam";
$labels['delete'] = "Eliminar correos electrónicos que parecen ser spam";
$labels['success'] = "Guardado exitosamente";
$labels['save_error'] = "Error mientras se guardaba";
$labels['load_error'] = "Error mientras se cargaba";
