<?php
$labels['spam_vpopmaild'] = "Protection anti-pourriels";
$labels['spam_on_off'] = "Activer/désactiver la protection anti-pourriels";
$labels['detection'] = "Activer la protection anti-pourriels";
$labels['delete'] = "Effacer les courriels semblant être des pourriels";
$labels['success'] = "Enregistrement réussi";
$labels['save_error'] = "Erreur lors de l'enregistrement";
$labels['load_error'] = "Erreur lors du chargement";
