<?php
$labels['spam_vpopmaild'] = "Protección frente ao correo lixo";
$labels['spam_on_off'] = "Activar/desactivar protección fronte ao correo lixo";
$labels['detection'] = "Activar a detección do correo lixo";
$labels['delete'] = "Borrar mensaxes que semellan spam";
$labels['success'] = "Gardouse con éxito";
$labels['save_error'] = "Ocurriu un erro mentres se gardaba";
$labels['load_error'] = "Ocurriu un erro mentres se cargaba.";
